package common.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * entranceService service = new entranceService();
 * EntranceService portType = service.getEntranceServiceImplPort();
 * portType.excute(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "entranceService", targetNamespace = "http://entranceService.wondersgroup.com/", wsdlLocation = "http://59.225.200.64:8034/service-entrance/ws/entranceService?wsdl")
public class EntranceService_Service extends Service {

	private final static URL ENTRANCESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(web.EntranceService_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = web.EntranceService_Service.class.getResource(".");
			url = new URL(baseUrl, "http://59.225.200.64:8034/service-entrance/ws/entranceService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://59.225.200.64:8034/service-entrance/ws/entranceService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ENTRANCESERVICE_WSDL_LOCATION = url;
	}

	public EntranceService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EntranceService_Service() {
		super(ENTRANCESERVICE_WSDL_LOCATION, new QName(
				"http://entranceService.wondersgroup.com/", "entranceService"));
	}

	/**
	 * 
	 * @return returns EntranceService
	 */
	@WebEndpoint(name = "EntranceServiceImplPort")
	public EntranceService getEntranceServiceImplPort() {
		return super.getPort(new QName(
				"http://entranceService.wondersgroup.com/",
				"EntranceServiceImplPort"), EntranceService.class);
	}

}
